#theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Spencer Emmons
color-scheme: dark
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/semmons98
navigation:
  - name: Home
    link: https://semmons98.github.io/
  - name: Research
    link: ./research/
  - name: Programming
    link: ./programming/
