#theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Spencer Emmons
color-scheme: dark
platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/spencer-emmons
navigation:
  - name: Home
    link: https://semmons98.github.io/
  - name: Research
    link: https://semmons98.github.io/research/
  - name: Programming
    link: https://semmons98.github.io/programming/
  - name: Science Outreach and Education
    link: https://semmons98.github.io/science_outreach/
  - name: Game Design
    link: https://semmons98.github.io/games/
